### ISSUE TITLE
SyntaxError: Unexpected token F in JSON at position 0

### ISSUE THREAD

**Issue by bit-crafter** [deanWombourne/bitrise-step-diawi-upload#3]

**Comment by deanWombourne** [comment]
Hi - we're using this on our CI without any issues so can't reproduce this. Do you have any more details please?

**Comment by deanWombourne** [comment]
Hi - I haven't seen this, and no-one else has reported it, so unless there are any more details you can help with, I'm going to close this ticket as unreproducible.

Thanks.

**Comment by LibertyVinova** [comment]
Hi, I have faced this issue. I upload successfully with iOS and other app with both iOS and android. Dont know what this bug is. This is my log, I use android-build step also:
================== ANDROID build step
Used patterns for generated artifact search:
*/build/outputs/apk/*.apk
*/build/outputs/bundle/*.aab
Found app artifacts:
app-stg-release.apk
Exporting artifacts with the selected app type: apk
  Export [ app-stg-release.apk => $BITRISE_DEPLOY_DIR/app-stg-release.apk ]
  Env    [ $BITRISE_APK_PATH = $BITRISE_DEPLOY_DIR/app-stg-release.apk ]
  Env    [ $BITRISE_APK_PATH_LIST = $BITRISE_DEPLOY_DIR/app-stg-release.apk ]
Export mapping files:
No mapping files found with pattern: *build/*/mapping.txt
You might have changed default mapping file export path in your gradle files or obfuscation is not enabled in your project.
================== DIAWI step
Running command 'diawi upload [REDACTED] /Users/vagrant/deploy/app-stg-release.apk'
Failed:  Error: SyntaxError: Unexpected token F in JSON at position 0
    at Diawi.onUploadComplete (/usr/local/lib/node_modules/diawi/diawi.js:76:24)
    at Request.self.callback (/usr/local/lib/node_modules/diawi/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/diawi/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/diawi/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by thaiphandinh** [comment]
![image](https://user-images.githubusercontent.com/79837212/150432553-a92b7a61-da38-412e-ad39-4ef4494a4e2c.png)
I have jumped to the same situation today. Any update on this @deanWombourne ?
I would be glad to provide some more information if needed.

**Comment by phungnlg** [comment]
I got the same issue

**Comment by thaiphandinh** [comment]
in my case, it was because the File I tried to upload was too big. So, it might be helpful to check you file size.
